# Makefile
# 
# Objetivo: Rodar exemplo da barra de progresso no dialog.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 31/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	exemplo.sh
	(./exemplo.sh) | dialog --title "Exemplo" --gauge "Barra de progresso" 10 40
