#!/bin/bash
#
# build_header.sh (Shell Script)
# 
# Objetivo: Script para gerar arquivo header a partir de um arquivo de definição de funções.
#
# Este script utiliza os marcadores /*< e >*/ para separar a ajuda das funções e a REGEX para
# selecionar as funções a partir do arquivo pilha.c e montar o cabeçalho exibido na tela do 
# terminal.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 25/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

FILENAME="pilha.c"
FILE=${FILENAME%%.c}
HEADER="_${FILE~~}_H_"

echo -e "/* This file is automatically generated. DO NOT EDIT! */\n\n#ifndef $HEADER\n#define $HEADER\n"

sed -n -r -e '/(\b(void|int|float|double|bool)\b ([^main][A-Za-z0-9_]+)\([A-Za-z\*,\\\/ ]+\)|\/\*<)/p' $FILENAME | sed '/)/s/$/;/' | sed '/\/*<.*>*\//s/$/\n/'

echo -e "\n#endif"
