from rsf.tex import *
import os
import glob

# Run the experiment with scons
print('Running experiment with scons...')
os.chdir('scons/')
os.system('scons')

# Build figures
print('Building figures...')
os.chdir('Fig/')
listOfFigures = glob.glob('*.vpl')

for i in listOfFigures:
	i = i.split('.')[0]
	print('Building '+str(i)+'.pdf')
	string = 'jpegpen <'+str(i)+'.vpl bgcolor=w >'+str(i)+'.jp2'
	os.system(string)
	string = 'img2pdf <'+str(i)+'.jp2 >'+str(i)+'.pdf'
	os.system(string)

print('Building reproducible papper...')
os.chdir('../..')

End(options='manuscript',use=['[bookmarks=true]hyperref','amsmath','color','listings'])
