# Makefile 
# 
# Objetivo: Compilação do estudo sobre bool e enum.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 03/11/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	exemplo.x

exemplo.x:	exemplo.c
	gcc -g exemplo.c -o exemplo.x

clean:
	rm *.x

.PHONY:	clean
