# Makefile 
# 
# Objetivo: Compilação do estudo sobre ponteiros de estruturas em C - segunda parte.
# 
# Versão 1.0
# 
# Site: http://www.dirackslounge.online
# 
# Programador: Rodolfo A. C. Neves (Dirack) 04/07/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

CC = gcc
EXE = estudoPonteiros.x

all:	$(EXE) run

run:	$(EXE)
	./$<

%.x:	%.c
	$(CC) $< -o $@
