#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct
# 
# Objetivo: Estudo sobre backtick function: rodar um comando do shell e capturar o output.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 01/06/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

files = Glob("*.c")
print(files)

Program('hello.x',files)
