#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre importação de módulos e utilização de flags no scons.
# Rode 'scons -I modulos --debug=time' para executar este exemplo,
#
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 17/05/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

import modulo

print("A soma 1+2="+str(modulo.soma(1,2)))
