# Makefile 
# 
# Objetivo: Compilação do estudo sobre execução de eventos com jframe do java.
# 
# Versão 1.0
# 
# Site: http://www.dirackslounge.online
# 
# Programador: Rodolfo A. C. Neves (Dirack) 28/06/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

CC = javac

all:	Clicado.class Principal.class

%.class:	%.java
	$(CC) $<

run:
	java Principal

clean:
	rm *.class
