#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generateSelfdoc  (SConscript)
#
# Purpose: Generate selfdoc for Madagascar recipes using pydoc.
# 
# Important!: It should be called from 'scons' with the command
# 'scons -f generateSelfdoc' 
#
# Site: http://www.dirackslounge.online
# 
# Version 1.0
#
# Programer: Rodolfo A. C. Neves (Dirack) 04/03/2020
#
# Email: rodolfo_profissional@hotmail.com
#
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

import pydoc

RECIPES=['kimodel',
	'pefInterpolation']

for i in RECIPES:
	pydoc.writedoc(i)
