#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generateSelfdoc  (SConscript)
#
# Purpose: Generate selfdoc for Madagascar recipes using pydoc.
#
# Important!: It should be called from 'scons' with the command
# 'scons -f generateSelfdoc'
#
# Site: http://www.dirackslounge.online
#
# Version 1.0
#
# Programer: Rodolfo A. C. Neves (Dirack) 04/03/2020
#
# Email: rodolfo_profissional@hotmail.com
#
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.
'''
Esse é um exemplo de uso de docstrings
com o help do scons
apenas um exemplo
'''

__author__="Rodolfo Dirack <rodolfo_profissional@hotmail.com>"
__version__="1.0"

def funcao():
    """
    Uma função inútil
    recebe nada de parametros
    """
    print("Teste!!!")

Help(__doc__)
Help(funcao.__doc__)
