# SConstruct (Python)
# 
# Objetivo:
# 
# Versão
# 
# Site:
# 
# Programador: 10/09/2020
# 
# Email:
# 
# Licença:

from rsf.proj import *

Flow('vp',None,
	'''
	spike n1=200 n2=400 d1=0.004 d2=0.025 o1=0 o2=0 k1=1,101 l1=100,200 mag=2,3 nsp=2
	''')

# plot the input velocity.  Use allpos=y to plot velocity.
Result('vp',
       '''
       grey color=j titlefat=4 titlesz=8 labelfat=4 labelsz=8
            screenratio=1.0 barwidth=0.6
            allpos=y scalebar=y n1tic=50 n2tic=40 verb=y
            title="Original Velocity"
       ''')

End()
