# Generated by Django 5.1.4 on 2024-12-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='topic')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200, verbose_name='entry')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
