# Makefile
# 
# Objetivo: Compilação do estudo sobre o método Runge-Kutta.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 02/01/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

main.x:	main.c runge.h
	gcc -g $< -o $@

clean:
	rm *.x

.PHONY:	clean
