#!/bin/bash
#
# teste (Shell Script)
# 
# Objetivo: Correção automatizada de exercício.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 16/04/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

[ ! -f "exercicio.x" ] && {
	echo "Arquivo exercicio.c não encontrado!"
	exit 1
}

CHECK=$(./exercicio.x 2>&1)
STRING="34.800000, 21, Rodolfo"
if [ "$CHECK" == "$STRING" ]
then
	echo "Teste passou!"
	exit 0
else
	echo -e "Teste falhou!\nResultado: $CHECK Esperado: $STRING"
	exit 1
fi
