#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre Alias Install do SCons.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 01/06/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

env = Environment()
hello = env.Program('hello.x','hello.c')
goodbye = env.Program('goodbye.x','goodbye.c')
env.Install('pasta', [hello, goodbye])
env.Alias('install', 'pasta')
    
