#!/bin/bash
#
# log2tex (Shell Script)
# 
# Objetivo: Script para converter o arquivo de log para o formato latex.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 10/09/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

FILENAME=$(basename "$1" | cut -d'.' -f1)
LATEXFILENAME="$FILENAME.tex"
FILE=$(cat "$FILENAME.log")

echo '\section{Logfile dos experimentos}' > "$LATEXFILENAME"
echo '\begin{verbatim}' >> "$LATEXFILENAME"
echo "$FILE" >> "$LATEXFILENAME"
echo '\end{verbatim}' >> "$LATEXFILENAME"


