#!/usr/bin/env python
#
# coding: utf-8
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre como fazer um building monitorado com um relatório de erros.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 10/09/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.tex import *
import os
import logging

logging.basicConfig(level=logging.DEBUG,format='%(asctime)s - %(message)s')


env =  Environment(ENV=os.environ)

experiments = filter(os.path.isdir,os.listdir(os.path.curdir))
sconscripts = filter(os.path.isfile,map(lambda e: str(e)+'/SConscript',experiments))

logging.debug('experiments = %s' % experiments)
logging.debug('sconscripts = %s' % sconscripts)

for i in sconscripts:
	try:
		SConscript(i,exports='env')
	except:
		logging.debug("Experiment %s Failed!",i)


#SConscript(sconscripts[0],exports='env')
#SConscript(sconscripts[1],exports='env')

#End(options='reproduce',
#	     include=r'''
#	     \usepackage[utf8]{inputenc}
#	     ''')
