#!/usr/bin/env python
#
# coding: utf-8
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre como fazer um building monitorado com um relatório de erros.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 10/09/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.tex import *
from rsf.proj import Flow
import os
import logging

logging.basicConfig(filename='out.log',level=logging.INFO,
			format='%(asctime)s - %(levelname)s - %(message)s')

logging.info('***[Experiment Started]***')

env =  Environment(ENV=os.environ)

experiments = filter(os.path.isdir,os.listdir(os.path.curdir))
sconscripts = filter(os.path.isfile,map(lambda e: str(e)+'/SConscript',experiments))

logging.debug('experiments = %s' % experiments)
logging.debug('sconscripts = %s' % sconscripts)

for i in sconscripts:
	try:
		SConscript(i,exports='env')
		logging.info("Expement %s Succed!",i)
	except:
		logging.error("Experiment %s Failed!",i)
		currentExperimentDir = os.path.dirname(i)
		logging.warning(
		'''Experiment Failed - Show files list\n\t Files=> %s
		''', str(os.listdir(currentExperimentDir)))
		
		if os.path.isdir(currentExperimentDir+'/'+'Fig'):
			logging.warning(
			'''Experiment Failed - Show Fig list\n\t Fig=> %s
			''', str(os.listdir(currentExperimentDir+'/'+'Fig')))
		
		# Try to run a BUGSCRIPT (This is a SConscript with another name
		# to allow the experiment to do a set of commands if the build fails)
		if os.path.isfile(currentExperimentDir+'/BUGSCRIPT'):
			try:
				SConscript(currentExperimentDir+'/BUGSCRIPT')
			except:
				logging.warning("BUGSCRIPT failed!")

logging.disable(logging.CRITICAL)
Flow('out.tex',None,
	'''
	./log2tex %s
	''' %('out.log'))

End(options='reproduce',
	     include=r'''
	     \usepackage[utf8]{inputenc}
	     ''')
