# Makefile
# 
# Objetivo: Compilar exemplo de armazenamento de estruturas em arquivo binário.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 23/10/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	usuarios.h gera_binario_usuarios.x ler_usuarios.x

%.x:	%.c
	gcc $< -o $@
