# Makefile 
# 
# Objetivo: Compilação lista Dinâmica encadeada
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 27/12/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	listaDinEncadeada.h main.x

main.x:	listaDinEncadeada.c main.c
	gcc -g $^ -o $@

clean:
	rm *.x

.PHONY:	clean
