#!/usr/bin/env python
#
# coding: utf-8
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre reproducible documents com Madagascar e Scons.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 10/09/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.tex import *
import os

env = Environment(ENV=os.environ)
env.Command('experiments/Fig/figure.pdf','experiments/Fig/figure.vpl',
	    '<$SOURCE '+str(env['ENV']['RSFROOT'])+'/bin/pdfpen > $TARGET')

End(options='reproduce',
	include=r'''
	\usepackage[utf8]{inputenc}
	''')
