#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre Builders em SCons.
# Este builder irá fazer uma cópia de um arquivo
# chamado teste.txt em um arquivo teste.bak
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 05/10/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.


jalbld = Builder(action='cp $SOURCES $TARGET',
                 suffix = '.bak',
                 src_suffix = '.txt')
env = Environment(BUILDERS={'Jal' : jalbld})

env.Jal('teste','teste')

