#!/bin/bash
#
# Makefile
# 
# Objetivo: Rodar a suíte de testes com Unity.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 21/09/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:
	gcc TestDumbExample.c DumbExample.c src/unity.c -o TestDumbExample
	./TestDumbExample
