# Makefile 
# 
# Objetivo: Compilação do programa lista encadeada.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 02/12/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	listaEncadeada.x

listaEncadeada.x:	listaEncadeada.c
	gcc listaEncadeada.c -o listaEncadeada.x

clean:
	rm *.x
