# Makefile
# 
# Objetivo: Compilação do estudo sobre Shell command em C.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 03/11/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	system.x

system.x:	system.c
	gcc system.c -o system.x
