# Makefile
# 
# Objetivo: Compilação do exemplo main para ser usado com o GDB.
# Após compilar use o comando 'gdb main.x' para depurar com GDB.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 04/01/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

main.x:	main.c
	gcc -g $< -o $@

clean:
	rm *.x

.PHONY:	clean
