# Makefile 
# 
# Objetivo: Compilação do exemplo sobre TAD - ponto 2D.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 08/11/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	exemplo.x

exemplo.x:	exemplo.c ponto.c ponto.h
	gcc ponto.c exemplo.c -o exemplo.x -lm
