apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-container
        image: flask-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: GREETING_MESSAGE
          value: "olá direto do deployment!"
        - name: PORT
          value: "5000"
