#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct  (Madagascar Script)
#
# Purpose: Common Reflection Element (CRE) stack applied to a seismic data cube
# from Kirchhoff modeling of a gaussian reflector in a linear velocity model.
#
# Site: https://dirack.github.io
# 
#def CheckMyLibrary(context):
 #       context.Message('Checking for Test...')
  ##      result = context.TryLink(mylib_test_source_file, '.c')
   #     context.Result(result)
    #    return result
from rsf.proj import *

test = Flow('teste.rsf',None,'spike n1=10')
#AddPostAction(test,print(str(test[0])))
End()
