#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SConstruct (Madagascar Script)
# 
# Purpose: Remove tmp files and execute shell commands in sequence.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programmer: Rodolfo A C Neves (Dirack) 08/10/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

# Tmp files
tmps = ['tmp1','tmp2','tmp3']

Flow('teste',None,
	'''
	spike n1=10 >${TARGETS[0]};
	$RSFROOT/bin/sfspike n1=20 > tmp1;
	$RSFROOT/bin/sfspike n1=20 > tmp2;
	$RSFROOT/bin/sfspike n1=20 > tmp3;
	$RSFROOT/bin/sfrm %s
	'''%(' '.join(tmps)),stdout=0)

End()
