#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Objetivo: Estudo sobre o builder Split do scons.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 17/05/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.


src_files = Split('''main.c
		file1.c
		file2.c''')
Program(target='program.x',source=src_files)
